server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: password
      database: departments
      port: 27017
      host: localhost